[target.'cfg(target_arch = "wasm32")']
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[target.aarch64-unknown-linux-gnu]
linker = "/origin/home/jmjoy/workspace/trimui/toolchain/bin/aarch64-linux-gnu-gcc"
